version: "3.9"
services:
  ppoba-db:
    image: "mysql:8.0"
    container_name: ppoba-db
    restart: always
    ports:
      - "3316:3306"
    volumes:
      - ./database:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ppoba
      MYSQL_DATABASE: ppoba
      MYSQL_USER: root
      MYSQL_PASSWORD: ppoba
    networks:
      - test_network

  ppoba-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: amazoncorretto:11
    container_name: ppoba-backend
#    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - "9990:9991"
    volumes:
      - ./build/libs/ppoba-0.0.1-SNAPSHOT.jar:/ppoba.jar
    entrypoint: ["java", "-jar", "/ppoba.jar"]
    networks:
      - test_network

networks:
  test_network:
